references:
  workspace_root: &workspace_root /home/circleci/my-workspace

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

version: 2
jobs:
  install:
    working_directory: *workspace_root
    docker:
      - image: circleci/node:10
    steps:
      - checkout

      - run: |
          npm ci

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - node_modules/

  lint:
    working_directory: *workspace_root
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - *attach_workspace

      - run: |
          npm run lint
          npm run prettier:check

  build:
    working_directory: *workspace_root
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - *attach_workspace

      - run: |
          npm run build

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - build/

  lib/build:
    working_directory: *workspace_root
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - *attach_workspace

      - run: |
          npm run lib:build
          npm run lib:build:compressed

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - public/

  deploy:
    working_directory: *workspace_root
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - *attach_workspace

      - run: |
          cp -r public/lib build
          ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN --non-interactive

  publish/beta:
    working_directory: *workspace_root
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - *attach_workspace
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Copy package and readme
          command: cp package.json public/lib/ && cp README.md public/lib/
      - run:
          name: Publish package
          command: npm publish public/lib --tag beta --access public

  publish:
    working_directory: *workspace_root
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - *attach_workspace
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Copy package and readme
          command: cp package.json public/lib/ && cp README.md public/lib/
      - run:
          name: Publish package
          command: npm publish public/lib --access public

workflows:
  version: 2
  build-deploy:
    jobs:
      - install
      - lint:
          requires:
            - install
          filters:
            tags:
              only: /^v.*/
      - build:
          requires:
            - install
      - lib/build:
          requires:
            - install
          filters:
            tags:
              only: /^v.*/
      - deploy:
          requires:
            - lint
            - lib/build
            - build
          filters:
            branches:
              only: master
      - publish/beta:
          context: npm-org
          requires:
            -
            - lib/build
            - lint
          filters:
            branches:
              only: master
      - publish:
          context: npm-org
          requires:
            - lib/build
            - lint
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
